config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

devise_scope :user do
  authenticated :user do
    root 'home#index', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end
  get 'home/index'
  get 'home/show'

  resources :resturants
  resources :dishes
  resources :ingredients
  root :to => 'home#index'
  #root :to => "devise/sessions#new"
end

app/models/resturant.rb
class Resturant < ActiveRecord::Base
  has_many :menus, dependent: :destroy
  has_many :dishes, :through => :menus
  has_many :inventories, dependent: :destroy
  has_many :ingredients, :through => :inventories
  belongs_to :admin
  resourcify
end

app/controllers/resturants_controller.rb
class ResturantsController < ApplicationController
  before_action :authenticate_admin!, :except => [:index, :show]
  def index
    @resturants = Resturant.all
  end

  def show
    @resturant = Resturant.find(params[:id])
    @ingredients = Ingredient.all

  end

  def new
		@resturant = current_admin.resturants.build
	end

	def create
		@resturant = current_admin.resturants.build(resturant_params)
		if @resturant.save
			redirect_to resturants_path, :notice => "This resturant has been added to our records."
		else
			render "new"
		end
	end

	def edit
		@resturant = Resturant.find(params[:id])
	end

	def update
		@resturant = Resturant.find(params[:id])
		if @resturant.update_attributes(resturant_params)
			redirect_to resturant_path, :notice => "This resturant has been updated in our records."
		else
			render "edit"
		end
	end

	def destroy
		@resturant = Resturant.find(params[:id])
		@resturant.destroy
		redirect_to resturants_path, :notice => "This Resturant has been deleted."
	end

	private

	def resturant_params
    params.require(:resturant).permit(:name, :email, ingredient_ids: [])
	end
end

app/helpers/resturants_helper.rb
module ResturantsHelper
end

app/views/resturants/edit.html.haml
%h3 Edit Resturant

= form_for @resturant do |f|
  %p
    = f.label :name
    = f.text_field :name


  %p
    = f.label :email
    = f.email_field :email, autofocus: true


  - if current_admin.has_role? :resturant_owner
    %p
      = f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |b|
        = b.check_box
        = b.label
  %p
    = f.submit "Update Resturant"

%h5
  = link_to "Go Back", resturant_path

app/views/resturants/index.html.haml
%h2 All Resturants

- @resturants.each do |resturant|
  %h4
    = link_to resturant.name, resturant_path(:id => resturant.id)


%h5
  - if admin_signed_in?
    - if current_admin.has_role? :super_admin
      = link_to "Add new Resturant", new_resturant_path
      &nbsp;
      |
      &nbsp;
    = link_to "Back to Homepage", home_index_path
  - else
    = link_to "Back to Homepage", home_index_path

app/views/resturants/new.html.haml
%h3 Add new Resturant

= form_for @resturant do |f|
  %p
    = f.label :name
    = f.text_field :name

  %p
    = f.label :email
    = f.email_field :email, autofocus: true

  /
    %p

      = f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |b|
        = b.check_box
        = b.label
  %p
    = f.submit "Add Resturant"

%h4
  = link_to "Go Back", resturants_path

app/views/resturants/show.html.haml
%h3
  = @resturant.name

%h4 This resturant has the following Ingredients :

- if @resturant.ingredient_ids.present?
  - @resturant.ingredient_ids.each do |ingredient_id|

    %h4

      =link_to @ingredients.find(ingredient_id).name, @ingredients.find(ingredient_id)

- else
  %p Sorry! There are no ingredients available for this resturant right now.


%h5
  - if admin_signed_in?
    = link_to "Return to all Resturants.", resturants_path
    - if @resturant.email == current_admin.email

      &nbsp;
      |
      &nbsp;
      = link_to "Edit this Resturant", edit_resturant_path
    - if current_admin.has_role? :super_admin
      &nbsp;
      |
      &nbsp;
      = link_to "Edit this Resturant", edit_resturant_path
      &nbsp;
      |
      &nbsp;
      = link_to 'Delete this Resturant', @resturant, :method => :delete, data: { confirm: 'Are you sure?' }
  - else
    = link_to "Return to all Resturants.", resturants_path