config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

devise_scope :user do
  authenticated :user do
    root 'home#index', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end
  get 'home/index'
  get 'home/show'

  resources :resturants
  resources :dishes
  resources :ingredients
  root :to => 'home#index'
  #root :to => "devise/sessions#new"
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :meals, dependent: :destroy
  has_many :dishes, :through => :meals
  has_many :inventories, dependent: :destroy
  has_many :resturants, :through => :inventories
  belongs_to :admin
  resourcify
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :authenticate_admin!, :except => [:index, :show]
  def index
    @ingredients = Ingredient.all
  end

  def show
    @ingredients = Ingredient.find(params[:id])
    @dishes = Dish.all
    @resturants = @ingredients.resturants
  end

  def new
		@ingredient = current_admin.ingredients.build
	end

	def create
		@ingredient = current_admin.ingredients.build(ingredient_params)
		if @ingredient.save
			redirect_to ingredients_path, :notice => "This ingredient has been added to our records."
		else
			render "new"
		end
	end

	def edit
		@ingredient = Ingredient.find(params[:id])
	end

	def update
		@ingredient = Ingredient.find(params[:id])
		if @ingredient.update_attributes(ingredient_params)
			redirect_to ingredient_path, :notice => "This ingredient has been updated in our records."
		else
			render "edit"
		end
	end

	def destroy
		@ingredient = Ingredient.find(params[:id])
		@ingredient.destroy
		redirect_to ingredients_path, :notice => "This Ingredient has been deleted."
	end

	private

	def ingredient_params
    params.require(:ingredient).permit(:name)
	end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/edit.html.haml
%h3 Edit Ingredient

= form_for @ingredient do |f|
  %p
    = f.label :name
    = f.text_field :name

  %p
    = f.submit "Update Ingredient"

%h4
  = link_to "Go Back", ingredient_path

app/views/ingredients/index.html.haml
%h1 List of all the ingredients

- @ingredients.each do |ingredient|
  %h4
    = link_to ingredient.name, ingredient
%h5
  - if admin_signed_in?
    - if current_admin.has_role? :super_admin
      = link_to "Add new Ingredient", new_ingredient_path
      &nbsp;
      |
      &nbsp;
    = link_to "Back to Homepage", home_index_path
  - else
    = link_to "Back to Homepage", home_index_path

app/views/ingredients/new.html.haml
%h3 Add new Ingredient

= form_for @ingredient do |f|
  %p
    = f.label :name
    = f.text_field :name

  %p
    = f.submit "Add Ingredient"

%h5
  = link_to "Go Back", ingredients_path

app/views/ingredients/show.html.haml
%h3
  = @ingredients.name
%h4
  /These are the dishes made with
  &nbsp;
  &nbsp;
  Description of the Ingredient.

%h5
  - if admin_signed_in?
    = link_to "Return to all Ingredients.", ingredients_path
    - if current_admin.has_role? :super_admin
      &nbsp;
      |
      &nbsp;
      = link_to "Edit this Ingredient", edit_ingredient_path
      &nbsp;
      |
      &nbsp;
      = link_to 'Delete this Ingredient', @ingredient, :method => :delete, data: { confirm: 'Are you sure?' }

  - else
    = link_to "Return to all Ingredients.", ingredients_path

app/views/ingredients/show.html_BACKUP_6270.haml
%h3
  These are the dishes made with
  = @ingredients.name
  \:
  %ul
    - @ingredients.dish_ids.each do |dish_id|
      %li
        = link_to @dishes.find(dish_id).title, @dishes.find(dish_id)
<<<<<<< HEAD

  and these are the resturants that serve this dish :

  %ul
    - @ingredients.dish_ids.each do |dish_id|
      - @dishes.find(dish_id).resturant_ids.each do |resturant_id|
        %li
          = link_to @resturants.find(resturant_id).name, @resturants.find(resturant_id)

%h5
  = link_to "Return to all Ingredients.", ingredients_path
=======
  %p These are the resturants where this ingredient is available :
  %ul
    - @resturants.each do |resturant|
      %li
        = link_to resturant.name, resturant

%h5
  = link_to "Back to all Ingredients.", ingredients_path
>>>>>>> feature/user-authentication

app/views/ingredients/show.html_BASE_6270.haml
%h3
  These are the dishes made with 
  = @ingredients.name
  \:
  %ul
    - @ingredients.dish_ids.each do |dish_id|
      %li
        = link_to @dishes.find(dish_id).title, @dishes.find(dish_id)
  and these are the resturants that serve this dish :
  %ul
    - @ingredients.dish_ids.each do |dish_id|
      - @dishes.find(dish_id).resturant_ids.each do |resturant_id|
        %li
          = link_to @resturants.find(resturant_id).name, @resturants.find(resturant_id)

app/views/ingredients/show.html_LOCAL_6270.haml
%h3
  These are the dishes made with 
  = @ingredients.name
  \:
  %ul
    - @ingredients.dish_ids.each do |dish_id|
      %li
        = link_to @dishes.find(dish_id).title, @dishes.find(dish_id)

  and these are the resturants that serve this dish :

  %ul
    - @ingredients.dish_ids.each do |dish_id|
      - @dishes.find(dish_id).resturant_ids.each do |resturant_id|
        %li
          = link_to @resturants.find(resturant_id).name, @resturants.find(resturant_id)

%h5
  = link_to "Return to all Ingredients.", ingredients_path

app/views/ingredients/show.html_REMOTE_6270.haml
%h3
  These are the dishes made with
  = @ingredients.name
  \:
  %ul
    - @ingredients.dish_ids.each do |dish_id|
      %li
        = link_to @dishes.find(dish_id).title, @dishes.find(dish_id)
  %p These are the resturants where this ingredient is available :
  %ul
    - @resturants.each do |resturant|
      %li
        = link_to resturant.name, resturant

%h5
  = link_to "Back to all Ingredients.", ingredients_path