config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

devise_scope :user do
  authenticated :user do
    root 'home#index', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end
  get 'home/index'
  get 'home/show'

  resources :resturants
  resources :dishes
  resources :ingredients
  root :to => 'home#index'
  #root :to => "devise/sessions#new"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    #@search = Resturant.search(params[:q])

   #@search = Ingredient.search(params[:q])
	 #@resturants = @search.result
  end



  def create
    #dish = params[:dish]
    #ingredient = params[:ingredient]
    #@resturants = Resturant.where(:email => @dish.admin.email).to_a
    #render :index
  end


  def show
    if params[:ingredient].present?
      @ingredient = Ingredient.find(params[:ingredient])
      @resturants = @ingredient.resturants
    end

    if params[:dish].present?
      @dish = Dish.find(params[:dish])
      @res = @dish.resturants
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
%h1
  Welcome to TomatoMint

%p
  %h4
    = link_to "All Resturants", resturants_path

    = link_to "All Dishes", dishes_path

    = link_to "All Ingredients", ingredients_path



%h4
  = form_tag("/home/show", method: "get") do
    = select_tag "ingredient", options_for_select(Ingredient.all.collect {|p| [ p.name, p.id ] }),{ include_blank: true }
    /= select("ingredient", "ingredient_id", Ingredient.all.collect {|p| [ p.name, p.id ] }, { include_blank: true })
    = select_tag "dish", options_for_select(Dish.all.collect {|p| [ p.title, p.id ] }),{ include_blank: true }
    = submit_tag("Search")

app/views/home/new.html.erb
<%= form_tag("/home/index", method: "post") do %>
  <%= label_tag :dish %><br>
  <%= text_field_tag :dish %>
  <br>
  <br>
  <%= label_tag :ingredient %><br>
  <%= text_field_tag :ingredient %>
  <p>
    <%= submit_tag("Submit") %>
  </p>
<% end %>

app/views/home/show.html.haml
%h1
  Welcome to TomatoMint

%p
  %h4
    = link_to "All Resturants", resturants_path

    = link_to "All Dishes", dishes_path

    = link_to "All Ingredients", ingredients_path



%h4 List of Resturants



- if @resturants.present?
  - @resturants.each do |resturant|
    %h4
      = link_to resturant.name, resturant
    %br
- else
  %h4 Sorry! No resturants for this ingredient.


%br



%br
- if @res.present?
  - @res.each do |rest|
    %h4
      = link_to rest.name, rest
    %br
- else
  %h4 Sorry! No resturant for this dish.