config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

devise_scope :user do
  authenticated :user do
    root 'home#index', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end
  get 'home/index'
  get 'home/show'

  resources :resturants
  resources :dishes
  resources :ingredients
  root :to => 'home#index'
  #root :to => "devise/sessions#new"
end

app/models/dish.rb
class Dish < ActiveRecord::Base
  has_many :menus, dependent: :destroy
  has_many :resturants, :through => :menus
  has_many :meals, dependent: :destroy
  has_many :ingredients, :through => :meals
  belongs_to :admin
  resourcify
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
	before_action :authenticate_admin!, :except => [:index, :show]


	def index
    @dishes = Dish.all
	end

	def show
    @dish = Dish.find(params[:id])
		@resturants = Resturant.all
		@ingredients = Ingredient.all

	end

	def new
		@dish = current_admin.dishes.build
	end

	def create
		@dish = current_admin.dishes.build(dish_params)
		if @dish.save
			redirect_to dishes_path, :notice => "This dish has been added to our records."
		else
			render "new"
		end
	end

	def edit
		@dish = Dish.find(params[:id])
		resturant_array = Resturant.where(:email => @dish.admin.email).to_a
		@resturant = resturant_array[0]
		@ingredients = @resturant.ingredients
	end

	def update
		@dish = Dish.find(params[:id])
		if @dish.update_attributes(dish_params)
			redirect_to dish_path, :notice => "This dish has been updated in our records."
		else
			render "edit"
		end
	end

	def destroy
		@dish = Dish.find(params[:id])
		@dish.destroy
		redirect_to dishes_path, :notice => "Your Dish has been deleted."
	end

	private

	def dish_params
    params.require(:dish).permit(:title, :body, :admin_id, ingredient_ids: [])
	end

end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/edit.html.haml
%h3 Edit Dish

= form_for @dish do |f|
  %p
    = f.label :title
    = f.text_field :title

  %p
    = f.label :body
    = f.text_area :body

  %p

    = f.collection_check_boxes :ingredient_ids, @ingredients, :id, :name do |b|
      = b.check_box
      = b.label
  %p
    = f.submit "Update Dish"

%h5
  = link_to "Go Back", dish_path

app/views/dishes/index.html.haml
%h1 All Dishes

- @dishes.each do |dish|
  %h4
    = link_to dish.title, dish


%h5
  - if admin_signed_in?
    - if current_admin.has_role? :resturant_owner
      = link_to "Add new Dish", new_dish_path
      &nbsp;
      |
      &nbsp;
    = link_to "Back to Homepage", home_index_path
  - else
    = link_to "Back to Homepage", home_index_path

app/views/dishes/new.html.haml
%h3 Add new Dish

= form_for @dish do |f|
  %p
    = f.label :title
    = f.text_field :title

  %p
    = f.label :body
    = f.text_area :body

  %p
    = f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |b|
      = b.check_box
      = b.label
  %p
    = f.submit "Add Dish"

%h5
  = link_to "Go Back", dishes_path

app/views/dishes/show.html.haml
%h1
  = @dish.title

%h6
  = @dish.created_at.strftime("%b %d, %Y")
  &nbsp;
  |
  &nbsp;
  Created By :
  = @dish.admin.email


%p
  = @dish.body

%h4 Ingredients :

- @dish.ingredient_ids.each do |ingredient_id|
  %h4
    =link_to @ingredients.find(ingredient_id).name, @ingredients.find(ingredient_id)

%h5
  - if admin_signed_in?
    = link_to "Return to all Dishes.", dishes_path
    - if @dish.admin == current_admin
      / It is assumed that a user has only one role out of admin, resturant_owner and normal user.
      - if current_admin.has_role? :resturant_owner
        &nbsp;
        |
        &nbsp;
        = link_to "Edit this Dish", edit_dish_path
        &nbsp;
        |
        &nbsp;
        = link_to 'Delete this Dish', @dish, :method => :delete, data: { confirm: 'Are you sure?' }
    - if current_admin.has_role? :super_admin
      &nbsp;
      |
      &nbsp;
      = link_to 'Delete this Dish', @dish, :method => :delete, data: { confirm: 'Are you sure?' }
  - else
    = link_to "Return to all Dishes.", dishes_path